yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "react-scripts@*":
    dependencies:
      "react-refresh": "*"
  "baseui@*":
    dependencies:
      "styletron-standard": "*"
  "baseui-virtual@*":
    dependencies:
      "styletron-standard": "*"